### ISSUE TITLE
Class Mpdf tidak tidemukan 

### ISSUE THREAD

**Issue by andeska-voyage** [basoro/mlite#147]
atal error: Uncaught Error: Class "Mpdf\Mpdf" not found in C:\xampp\htdocs\mlite\plugins\pasien\Admin.php:993 Stack trace: #0 [internal function]: Plugins\Pasien\Admin->getCetakRiwayatMpdf() #1 C:\xampp\htdocs\mlite\systems\Admin.php(87): call_user_func_array(Array, Array) #2 C:\xampp\htdocs\mlite\admin\index.php(30): Systems\Admin->loadModule('pasien', 'getCetakriwayat...') #3 [internal function]: {closure}('pasien', 'cetakriwayatmpd...', NULL) #4 C:\xampp\htdocs\mlite\systems\lib\Router.php(59): call_user_func_array(Object(Closure), Array) #5 C:\xampp\htdocs\mlite\admin\index.php(34): Systems\Lib\Router->execute() #6 {main} thrown in C:\xampp\htdocs\mlite\plugins\pasien\Admin.php on line 993
![Cuplikan layar 2024-02-03 181730](https://github.com/basoro/mlite/assets/69580176/2edb4129-f854-488f-86eb-6f6a42848006)

**Comment by basoro** [comment]
Silahkan jalankan perintah

`composer install`

Salam
