### ISSUE TITLE
Ga ada menu general concent dan inform concent

### ISSUE THREAD

**Issue by eg208** [basoro/mlite#159]
Bang request modul inform concent dan general concent

**Comment by basoro** [comment]
Coba sy buatkan

**Comment by 4RSIM3R** [comment]
mungkin untuk masukan pak dokter, nanti kata2 nya di buat dynamic aja, di simpen di db, karena mungkin masing masing faskes t&c nya beda beda

**Comment by doniaries** [comment]
suara panggil anjungan antrian apakah berfungsi pak?

**Comment by zulvikar07** [comment]
saat instal di hosting, ketika upload berkas digital (file .jpg), tidak bisa ditampilkan di riwayat perawatan pasien. hanya berupa icon gambar terbelah dua. ketika diklik, muncul peringatan DNS_PROBE_FINISHED_NXDOMAIN. 
link gambar tadi seperti ini : http://mlite.loc/webapps/berkasrawat/pages/upload/20240430000001_17144610510.jpg

jika dilihat di mlite demo, link gambar tadi harusnya tertulis alamat website dari hosting menggantikan tulisan mlite.loc/

izin dokter Basoro, bagaimana cara mengatasinya? 
terima kasih

**Comment by zulvikar07** [comment]
waah, terima kasih...
sudah bisa dok

ubahnya ternya di sini :
// URL Webapps
define('WEBAPPS_URL', 'http://mlite.loc/webapps');

**Comment by rsamjkt** [comment]
izin masukan dok, barangkali bisa dibuat untuk isian TTV pada soap otomatis terisi jika sudah input asesmen medis/asesmen keperawatan rajal

**Comment by basoro** [comment]
Coba sy buatkan

Sab, 11 Mei 2024 pukul 08.48 rsamjkt ***@***.***> menulis:

**Comment by basoro** [comment]
Silahkan update di https://github.com/basoro/mlite/pull/270/commits/a02d81c15ac23b3fc70c5e0a1ae9c23901fd0f6b
