### ISSUE TITLE
Tidak bisa menampilkan berkas digital di riwayat pasien pada mlite yang terpasang di hosting

### ISSUE THREAD

**Issue by zulvikar07** [basoro/mlite#169]
saat instal di hosting, ketika upload berkas digital (file .jpg), tidak bisa ditampilkan di riwayat perawatan pasien. hanya berupa icon gambar terbelah dua. ketika diklik, muncul peringatan DNS_PROBE_FINISHED_NXDOMAIN.
link gambar tadi seperti ini : http://mlite.loc/webapps/berkasrawat/pages/upload/20240430000001_17144610510.jpg

jika dilihat di mlite demo, link gambar tadi harusnya tertulis alamat website dari hosting menggantikan tulisan mlite.loc/

izin dokter Basoro, bagaimana cara mengatasinya?
terima kasih

**Comment by 4RSIM3R** [comment]
coba cek `config.php` nya pak
