### ISSUE TITLE
Object not found! Erorr 404 saat buka anjungan/poli

### ISSUE THREAD

**Issue by zulvikar07** [basoro/mlite#177]
Mohon pencerahannya dok

mlite sudah running di hosting web, ketika dipindahkan ke localhost, ubah config dan pindahkan database, bisa berjalan normal layaknya di hosting...
tapi pada saat buka menu anjungan, semua anjungan tidak bisa terbuka, muncul Object not found! Erorr 404 dengan detail seperti berikut :

Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404

localhost
Apache/2.4.54 (Unix) OpenSSL/1.1.1s PHP/7.4.33 mod_perl/2.0.12 Perl/v5.34.1

apa yang harus diubah dok?
terima kasih

**Comment by basoro** [comment]
Pastikan ada file .htaccess di root folder (sejajat systems)

Salam

**Comment by zulvikar07** [comment]
masih gagal dok 
ini localhostnya pakai xampp 7.4 di os MacOs Monterey

**Comment by zulvikar07** [comment]
Sekalian dok

bagaimana cara memunculkan pilihan surat keterangan sakit untuk pasien rawat jalan. di mlite teman bisa, di punya saya ga bisa dok.

mohon petunjuknya...

![Screen Shot 2024-07-26 at 10 05 52 PM](https://github.com/user-attachments/assets/eddaded0-fa93-4454-94e9-93a624f3627f)
![Screen Shot 2024-07-26 at 10 04 02 PM](https://github.com/user-attachments/assets/d45f10a6-a021-4439-ac27-9526e266b9cc)

**Comment by basoro** [comment]
Pastikan versi yg terinstall adalah versi terakhir
