### ISSUE TITLE
Pesan eror Ciluk baaa...

### ISSUE THREAD

**Issue by zulvikar07** [basoro/mlite#199]
Izin bertanya dokter..

Saya baru download mlite diinstal di localhost xampp (karena ini versi terbaru, gagal update langsung dari mlite)
databasenya diambil dari mlite yang sudah jalan sebelumnya di localhost xampp yang sama
namun ketika dijalankan, muncul tulisan 

Ciluk baaa......
Menghapus trade mark saya yaa....! Upsss....

mohon bantuannya dok...
terima kasih

**Comment by basoro** [comment]
Pastikan tabel mlite_settings ada isinya

Salam

**Comment by zulvikar07** [comment]
tabel mlite_settings ini lihat di mana yaa dok?

**Comment by basoro** [comment]
Di database sesuai config.php

Atau https://github.com/basoro/mlite/blob/master/mlite_only.sql#L379 bisa dijadikan referensi

Salam

**Comment by zulvikar07** [comment]
sudah ada isinya dok... 
databasenya hasil export dari mlite yang sudah dipakai sebelumnya...
begitu diimport ke mlite yang baru, sesuaikan config.php, tapi saat dijalankan muncul peringatan ciluk baa itu dok
