### ISSUE TITLE
Vedika

### ISSUE THREAD

**Issue by fathur23-n** [basoro/mlite#202]
Selamat Pagi dokter bas dan tim pengembang mlite yang lain. Mohon izin menginfokan terkait bug pada menu vedika, baik di index,lengkap atau pengajuan. Ketika kita mengunggah file pada fitur tersebut, dan kita coba untuk melakukan refresh halaman itu berkas yg kami unggah akan jadi dobel. Kemudian saya coba refresh lagi, nambah satu lagi berkas. Jadi kesimpulannya ketika kami mengunggah dan melakukan refresh itu datanya jadi nambah. Alhasi jadi data dobel2, mungkin next update bisa jadi pertimbangan. 

Terimakasih, salam :)

**Comment by basoro** [comment]
Ok... Saya cek dulu..

Terima kasih

**Comment by fathur23-n** [comment]
Siap dokter
